server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true&&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin


